### ISSUE TITLE
Another error after upgrading to 3.6

### ISSUE THREAD

**Issue by lukepass** [nelmio/NelmioApiDocBundle#1600]
After the upgrade I get this error on the API doc page:

```
Attempted to call an undefined method named "getDescription" of class "phpDocumentor\Reflection\DocBlock\Tags\InvalidTag".
```

What could it be related?

![image](https://user-images.githubusercontent.com/6429961/76100604-375d0980-5fcd-11ea-88db-07067ba73d16.png)

Thanks!

**Comment by maxhelias** [comment]
Please see #1598

**Comment by GuilhemN** [comment]
Fixed in #1598, thanks!

**Comment by lukepass** [comment]
I updated to the latest version but the error still persists. It seems related to this:

`Updating phpdocumentor/reflection-docblock (4.3.4 => 5.1.0)`

**Comment by B-Galati** [comment]
Same observation than @lukepass. Downgrading fixes the issue.

**Comment by GuilhemN** [comment]
This hadn't been released yet. It is now, see https://github.com/nelmio/NelmioApiDocBundle/releases :)

**Comment by B-Galati** [comment]
Thanks it works!
