### ISSUE TITLE
User Warning: operationId must be unique. Duplicate value found: ""

### ISSUE THREAD

**Issue by tarlepp** [nelmio/NelmioApiDocBundle#1967]
If I use following configuration (directly from recipe, just enabled that `/api/doc.json` path);
```
# Expose your documentation as JSON swagger compliant
app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

## Requires the Asset component and the Twig bundle
## $ composer require twig asset
app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
```

I get following error
```
User Warning: operationId must be unique. Duplicate value found: ""
```

And the error stack trace show me this;
```
/api/doc.json: {
	get: {
		operationId: null,
		responses: {
			default: {
				description: ""
			}
		}
	}
},
/api/doc: {
	get: {
		operationId: null,
		responses: {
			default: {
				description: ""
			}
		}
	}
}
```

And if I just comment out this part from configuration
```
app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }
```

No errors - but I really want to serve that `doc.json` too,

So that `operationId` is the _same_ in both of these - How can I fix this?

**Comment by DerManoMann** [comment]
Swagger-php 4.2.10 introduces a new validation rule for operation IDs.
You could rollback to the previous version but ultimately this should be fixed IMO; `null` is not a particularly useful if to start with and the specs expect it to be unique.
Leaving it out altogether might be better at least.

**Comment by DerManoMann** [comment]
swagger-php 4.2.11 will ignore 'null' opertation ids, although strictly speaking this should be a warning and fixed here in the bundle code.
https://github.com/zircote/swagger-php/issues/1153 does include some more details.

Bottom line is that it would be cleaner to remove the swagger-php `OperationId` processor rather than having another one that sets all values to `null`...

**Comment by rrajkomar** [comment]
FYI : I also had this at first. All I had to do was set the annotation correctly for all the routes within the areas defined in my config. Now I don't have this message anymore.

**Comment by GuilhemN** [comment]
I believe you are in the edge cases that were not fixed after https://github.com/nelmio/NelmioApiDocBundle/issues/1743 was reported.

Sorry for the delay, I'll work on a fix.
