### ISSUE TITLE
Version is only available reliably for validation and serialization

### ISSUE THREAD

**Issue by igordeveloper** [nelmio/NelmioApiDocBundle#1984]
I'm receiving the message below to generate a api doc after update in bundle zircote/swagger-php

**{"message":"Version is only available reliably for validation and serialization","code":0,"status":500}**

Below current configuration and version bundles:

```
nelmio/api-doc-bundle               v4.8.2
zircote/swagger-php                  v4.3.0
```

nelmio_api_doc.yaml
```
nelmio_api_doc:
    areas:
        path_patterns: # an array of regexps
        - ^/[a-z]
    documentation:
        openapi: 3.1.0
        components:
        ....
```
Any idea what configuration should be done to tell the openapi version?
Tks.

**Comment by DerManoMann** [comment]
Related to https://github.com/zircote/swagger-php/issues/1213.

The underlying change was made to allow to set the version in the `@OA\OpenApi` annotations. This means there is no reliable way to know the actual version until analysis is complete.

So, in order to avoid changing the version halfway through processing, attempts to use the version via the `Context` are rejected.

This is not an issue when using `swagger-php` standalone as the `Generator` class handles this internally.

That means setting the version via `Generator::setVersion()` still works, but access via the context is only guaranteed for processors, validation and serialization.

I would suspect the issue here is that annotation instances are created that do not share the context with the root context created by the generator (if that is used at all).

I am not familiar with many details of this project, but if you are happy to only support setting the version via your bundle config then setting the version in all `Context` instances created should solve this issue.

Ideally, all contexts should be child instances of a single root context. That allows to share things like version, logger and a couple other things across all code that has access.

**Comment by igordeveloper** [comment]
> Related to [zircote/swagger-php#1213](https://github.com/zircote/swagger-php/issues/1213).
> 
> The underlying change was made to allow to set the version in the `@OA\OpenApi` annotations. This means there is no reliable way to know the actual version until analysis is complete.
> 
> So, in order to avoid changing the version halfway through processing, attempts to use the version via the `Context` are rejected.
> 
> This is not an issue when using `swagger-php` standalone as the `Generator` class handles this internally.
> 
> That means setting the version via `Generator::setVersion()` still works, but access via the context is only guaranteed for processors, validation and serialization.
> 
> I would suspect the issue here is that annotation instances are created that do not share the context with the root context created by the generator (if that is used at all).
> 
> I am not familiar with many details of this project, but if you are happy to only support setting the version via your bundle config then setting the version in all `Context` instances created should solve this issue.
> 
> Ideally, all contexts should be child instances of a single root context. That allows to share things like version, logger and a couple other things across all code that has access.

Tks for explanation. We wiil wait for a feedback from Nelmio side.

**Comment by GuilhemN** [comment]
There were indeed several cases where annotations did not have the same root context. Thank you for the hint @DerManoMann!
I fixed those https://github.com/nelmio/NelmioApiDocBundle/pull/1988, and created a test case to make sure all our contexts have the same root. More generally, in the future when detecting similar Swagger-PHP API violations, we will now try to add test cases to remain compliant with your API assumptions.

@igordeveloper  Could you check whether https://github.com/nelmio/NelmioApiDocBundle/pull/1988 does indeed fix your issue?

**Comment by igordeveloper** [comment]
> There were indeed several cases where annotations did not have the same root context. Thank you for the hint @DerManoMann! I fixed those in #1988, and created a test case to make sure all our contexts have the same root. More generally, in the future when detecting similar Swagger-PHP API violations, we will now try to add test cases to remain compliant with your API assumptions.
> 
> @igordeveloper Could you check whether #1988 does indeed fix your issue?

HI.

I tryed with #1988 and the error persists.

tks

**Comment by igordeveloper** [comment]
> @igordeveloper Could you check whether #1988 does indeed fix your issue?

Hi.

I have tried with #1988 and the message error persists.

Tks.

**Comment by DerManoMann** [comment]
@GuilhemN sorry to push those onto you guys without warning, I'll try to give some more warning next time.

**Comment by GuilhemN** [comment]
@DerManoMann no problem, that's definitely not an easy topic, and that would have been complicated for you to know we were not using the modified API exactly the same as you in this bundle :) I was just stating this so you know we'll also try to make your maintenance easier and try to avoid worrying too much about this bundle ^^
(probably for the best that we improve context usage anyway, this should improve errors in many cases)

I'll investigate further during the week to find what other issue could cause the issue.

**Comment by GuilhemN** [comment]
@igordeveloper actually I tried reproducing your error in https://github.com/nelmio/NelmioApiDocBundle/pull/1992 and I was not able to.
I assumed from the error you described in https://github.com/zircote/swagger-php/issues/1213 that you were specifying a license in your configuration, and that was where things break.

Would you be able to create a minimal reproducer showing how to produce your error?

**Comment by igordeveloper** [comment]
> @igordeveloper actually I tried reproducing your error in #1992 and I was not able to. I assumed from the error you described in [zircote/swagger-php#1213](https://github.com/zircote/swagger-php/issues/1213) that you were specifying a license in your configuration, and that was where things break.
> 
> Would you be able to create a minimal reproducer showing how to produce your error?

In really, i'm not specifyng a license in my yaml configuration or annotation, im just specified the version open api in yaml conf, annotation and setting in my base controller.  Maybe now its a required field.

However, i will try set the license and send a new exception stacktrace .

**Comment by igordeveloper** [comment]
> @igordeveloper actually I tried reproducing your error in #1992 and I was not able to. I assumed from the error you described in [zircote/swagger-php#1213](https://github.com/zircote/swagger-php/issues/1213) that you were specifying a license in your configuration, and that was where things break.
> 
> Would you be able to create a minimal reproducer showing how to produce your error?

I tried with license field setted and the same error persists.


in [vendor/zircote/swagger-php/src/Context.php ](http://localhost:8000/_profiler/open?file=vendor/zircote/swagger-php/src/Context.php&line=125#line125)(line 125)

        if (!$this->version) {
            throw new \RuntimeException('Version is only available reliably for validation and serialization');
        }


The field openapi that i setted in yaml conf arrives correctly in this function,

**Comment by igordeveloper** [comment]
> @igordeveloper actually I tried reproducing your error in #1992 and I was not able to. I assumed from the error you described in [zircote/swagger-php#1213](https://github.com/zircote/swagger-php/issues/1213) that you were specifying a license in your configuration, and that was where things break.
> 
> Would you be able to create a minimal reproducer showing how to produce your error?

I cant found where the property $this->version is started.

**Comment by igordeveloper** [comment]
> @igordeveloper actually I tried reproducing your error in #1992 and I was not able to. I assumed from the error you described in [zircote/swagger-php#1213](https://github.com/zircote/swagger-php/issues/1213) that you were specifying a license in your configuration, and that was where things break.
> 
> Would you be able to create a minimal reproducer showing how to produce your error?

I'm using  the OpenApi annotation in my base api controller and i set the version api too in nelmio yaml , as below

```
 * @OA\OpenApi(
 *     openapi="3.1.0",
 *     @OA\Info(
 *         version="1.0.0",
 *         title="API",
 *         @OA\License(name="MIT", identifier="MIT")
 *     )
 * )

nelmio_api_doc:
    areas:
        path_patterns: # an array of regexps
        - ^/[a-z]
    documentation:
        openapi: '3.1.0'

```

Below exception stack trace
```

RuntimeException:
Version is only available reliably for validation and serialization

  at vendor/zircote/swagger-php/src/Context.php:125
  at OpenApi\Context->isVersion()
     (vendor/zircote/swagger-php/src/Annotations/License.php:93)
  at OpenApi\Annotations\License->validate()
     (vendor/zircote/swagger-php/src/Annotations/AbstractAnnotation.php:531)
  at OpenApi\Annotations\AbstractAnnotation::_validate()
     (vendor/zircote/swagger-php/src/Annotations/AbstractAnnotation.php:504)
  at OpenApi\Annotations\AbstractAnnotation->validate()
     (vendor/zircote/swagger-php/src/Annotations/AbstractAnnotation.php:531)
  at OpenApi\Annotations\AbstractAnnotation::_validate()
     (vendor/zircote/swagger-php/src/Annotations/AbstractAnnotation.php:504)
  at OpenApi\Annotations\AbstractAnnotation->validate()
     (vendor/zircote/swagger-php/src/Annotations/OpenApi.php:151)
  at OpenApi\Annotations\OpenApi->validate()
     (vendor/zircote/swagger-php/src/Analysis.php:438)
  at OpenApi\Analysis->validate()
     (vendor/nelmio/api-doc-bundle/ApiDocGenerator.php:124)
  at Nelmio\ApiDocBundle\ApiDocGenerator->generate()
     (vendor/nelmio/api-doc-bundle/Render/RenderOpenApi.php:74)
  at Nelmio\ApiDocBundle\Render\RenderOpenApi->render()
     (vendor/nelmio/api-doc-bundle/Render/RenderOpenApi.php:59)
  at Nelmio\ApiDocBundle\Render\RenderOpenApi->renderFromRequest()
     (vendor/nelmio/api-doc-bundle/Controller/SwaggerUiController.php:38)
  at Nelmio\ApiDocBundle\Controller\SwaggerUiController->__invoke()
     (vendor/symfony/http-kernel/HttpKernel.php:152)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (vendor/symfony/http-kernel/HttpKernel.php:74)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (vendor/symfony/http-kernel/Kernel.php:202)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php:35)
  at Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
     (vendor/autoload_runtime.php:35)
  at require_once('/app/vendor/autoload_runtime.php')
     (public/index.php:7) 
```

RuntimeException
in [vendor/zircote/swagger-php/src/Context.php ](http://localhost:8000/_profiler/open?file=vendor/zircote/swagger-php/src/Context.php&line=125#line125)(line 125)

```
     *
     @param string|array $versions One or more version numbers
     */
     public function isVersion($versions): bool
     {
     if (!$this->version) {
     	throw new \RuntimeException('Version is only available reliably for validation and serialization');
     } 
     ...
```
Until swagger-php 4.2.13 version was working correctly.

**Comment by igordeveloper** [comment]
> Related to [zircote/swagger-php#1213](https://github.com/zircote/swagger-php/issues/1213).
> 
> The underlying change was made to allow to set the version in the `@OA\OpenApi` annotations. This means there is no reliable way to know the actual version until analysis is complete.
> 
> So, in order to avoid changing the version halfway through processing, attempts to use the version via the `Context` are rejected.
> 
> This is not an issue when using `swagger-php` standalone as the `Generator` class handles this internally.
> 
> That means setting the version via `Generator::setVersion()` still works, but access via the context is only guaranteed for processors, validation and serialization.
> 
> I would suspect the issue here is that annotation instances are created that do not share the context with the root context created by the generator (if that is used at all).
> 
> I am not familiar with many details of this project, but if you are happy to only support setting the version via your bundle config then setting the version in all `Context` instances created should solve this issue.
> 
> Ideally, all contexts should be child instances of a single root context. That allows to share things like version, logger and a couple other things across all code that has access.


> @igordeveloper actually I tried reproducing your error in #1992 and I was not able to. I assumed from the error you described in [zircote/swagger-php#1213](https://github.com/zircote/swagger-php/issues/1213) that you were specifying a license in your configuration, and that was where things break.
> 
> Would you be able to create a minimal reproducer showing how to produce your error?

How related by @DerManoMann , i guess that even though I have set the openapi version via yaml file and in my controller base via annotation, all the other @OA\OpenApi annotations that I use in my controllers and dto's do not inherit the parent context.

 It is unfeasible that I seven one by one of these notes in the system,

**Comment by igordeveloper** [comment]
> @igordeveloper actually I tried reproducing your error in #1992 and I was not able to. I assumed from the error you described in [zircote/swagger-php#1213](https://github.com/zircote/swagger-php/issues/1213) that you were specifying a license in your configuration, and that was where things break.
> 
> Would you be able to create a minimal reproducer showing how to produce your error?

I found the problem.
The system is using a describer file with info and license, like https://github.com/nelmio/NelmioApiDocBundle/blob/master/Describer/DefaultDescriber.php,

If i set a license context equal api context, works fine, but i dont know if it is the correct way for solve this case.

  /** @var Info $info */
  $info->title = $composer->extra->projectTitle;
  $info->description = $composer->description;
  $info->version = $composer->version;
  $licence = new License([]);
  $licence->name = is_array($composer->license) ? implode(', ', $composer->license) : $composer->license;
  $licence->url = $composer->homepage;
  **$licence->_context = $api->_context;**
  $info->license = $licence

**Comment by igordeveloper** [comment]
> @igordeveloper actually I tried reproducing your error in #1992 and I was not able to. I assumed from the error you described in [zircote/swagger-php#1213](https://github.com/zircote/swagger-php/issues/1213) that you were specifying a license in your configuration, and that was where things break.
> 
> Would you be able to create a minimal reproducer showing how to produce your error?

Hi @GuilhemN .

How you mentioned license i did a new review in the system that I'm working and I can found the problem.
The system contains a describer and the describer license was being created without properties.

`$licence = new License([])`

I change for it: 

`$licence = Util::getChild($info, License::class);`

And now, the license receive the parent context correctly:

For me its not a bug in nelmio bundle or swagger-php.

Tks @GuilhemN and @DerManoMann
