### ISSUE TITLE
[Question]: Implementing generic classes discards the inferred type

### ISSUE THREAD

**Issue by mrazek-honza** [nelmio/NelmioApiDocBundle#2392]
### Version

4.29.0

### Question

Hello. I have a question regarding a use case that I encountered on our project. We have a response structure for paginated responses. The parent class is a generic and looks like this:
```php
/**
 * @template TData
 */
class PaginatedResponse
{
    /**
     * @param list<TData> $items
     */
    public function __construct(
        /** @var list<TData> */
        #[OA\Property(
            description: 'Array of requested items',
        )]
        public array $items,
        #[OA\Property(
            description: 'Number of all available items matching requested parameters',
            example: 69
        )]
        public int $totalSize,
    ) {
    }
}
```

The child class then implements the defined generic:

```php
/** @extends PaginatedResponse<CompanyResponse> */
final class CompanyListResponse extends PaginatedResponse
{
    public function __construct(
        /** @var list<CompanyResponse> $items */
        #[OA\Property(
            description: 'Array of requested Companies for specified or default page and page size',
        )]
        public array $items,
        int $totalSize,
    ) {
        parent::__construct(
            items: $this->items,
            totalSize: $totalSize,
        );
    }
}
```

This generates the desired schema, but there is a slight inconvenience in having to specify the `@var` annotation on every child class. When it is not specified, PHPStan (running on level 8) generates no errors, since the parent already specifies the type using the generic. However, the generated schema cannot infer the type properly and instead of generating  
```json
"items": {
   "$ref": "#/components/schemas/CompanyResponse"
}
```
it generates 
```json
"items": {}
```
 
My question is: Is there something wrong with our typing, or is this feature not supported by either this bundle, or the symfony property info components? Type hinting in the IDE works without specifying the `@var` tag in child components, so I suppose that PHPDocs are correct indeed.

Thank you for any answers.

**Comment by DjordyKoert** [comment]
I think this might be solved by https://github.com/nelmio/NelmioApiDocBundle/pull/2349 

You can try using this branch and seeing if this would solve your issue 👀 

```diff
// composer.json
-"nelmio/api-doc-bundle": "*",
+"nelmio/api-doc-bundle": "dev-2212-type-info",
```

And then opt in to this new behaviour by updating your bundle config `nelmio_api_doc.yaml`:
```yaml
nelmio_api_doc:
    experimental_type_info: true
```

NOTE: This is still a WIP so feedback is appreciated, I would love to hear if this would fix issues like these

**Comment by mrazek-honza** [comment]
@DjordyKoert  Thank you for so quick response. Sadly our project is running SF6.4 now, so I couldn't test it on the project itself.

I created a small sample application, where I generated the schema in initial commit and then tried to:
1. Remove the var tag https://github.com/mrazek-honza/nelmio-property-type-test/commit/563690261074d33c57c56b33c51331266bd0f54e 
2. Remove the override of parent class property https://github.com/mrazek-honza/nelmio-property-type-test/commit/ca65f2af4ca1dcfa3fcaf869b7a66b0330898d87

Sadly none of these helped, as you can see in these commits, the schema changes the same way.

I wonder if this is supported with property info utilities. I do not have insights into these, but if it is, I would love to help on this feature, since it is a valid use case in my eyes :)

**Comment by DjordyKoert** [comment]
This is most likely a restriction in `symfony/property-info`.

You could (temporarily) install only `symfony/property-info` on `^7.1` together with https://github.com/nelmio/NelmioApiDocBundle/issues/2392#issuecomment-2470198925 and see if this 'fixes' it.

**Comment by DjordyKoert** [comment]
I just found this open issue aswell for `symfony/property-info` to support generics https://github.com/symfony/symfony/issues/45071

**Comment by mrazek-honza** [comment]
I see, your searching skills are better :smile: I looked quickly through the issues on property-info but didn't find it. 

So if the issue gets implemented in the property-info component, it could be possible to reflect it in this bundle so that the type gets correctly inferred by generator?

**Comment by DjordyKoert** [comment]
Correct, but I mostly think this will be / is solved with the introduction of the TypeInfo component

**Comment by mario-fehr** [comment]
@DjordyKoert sorry commenting on this old issue but this issue still exists with 

- symfony 7.2
-  type info 7.2
- api-doc-bundle 5.0
- `type_info: true`

I made a [reproducer](https://github.com/mario-fehr/nelmioApiDocBundle-reproducer/tree/issue-2392) with the same steps @mrazek-honza did before:

1. [Remove the var tag](https://github.com/mario-fehr/nelmioApiDocBundle-reproducer/commit/4baa3a384645d200fb707750b86ce7738ea2ec73)
2. [Remove the override of parent class property](https://github.com/mario-fehr/nelmioApiDocBundle-reproducer/commit/cc922ca54276146dcbd6301ca1e9f07dcbacd4f7)
